"use client";

import React, { useState } from "react";
import Image from "next/image";
import { Clock, ArrowLeft, HelpCircle } from "lucide-react";
import { BlogCard1 } from "./BlogCard1";
import { ShareSection } from "./ShareSection";
import { Typography } from "@/app/components/ui/Typography";

export const Blog56 = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  return (
    <div className="w-full flex justify-center">
      {!isOpen ? (
        <div
          onClick={() => setIsOpen(true)}
          className="cursor-pointer w-full flex justify-center px-4"
        >
          <BlogCard1
            title="Loans Are Not Bad When Managed Properly: A Deep Dive into Strategic Debt"
            category="FINANCIAL PHILOSOPHY"
            author="Sumit Mishra"
            date="June 25, 2026"
            image="/images/blog/blog-56.jpeg"
          />
        </div>
      ) : (
        <div className="fixed inset-0 z-40 bg-white overflow-y-auto pt-20 md:pt-28 no-scrollbar animate-in fade-in duration-300 text-left">
          <div className="relative max-w-5xl mx-auto pb-20 px-4 md:px-6">
            <button
              onClick={() => setIsOpen(false)}
              className="flex items-center mb-6 text-gray-500 hover:text-[#1e3a8a] gap-1"
            >
              <ArrowLeft size={14} />
              <Typography variant="caption" className="font-bold uppercase">
                Back to Blogs
              </Typography>
            </button>

            <div className="bg-white rounded-xl overflow-hidden border border-gray-100 shadow-sm">
              <div className="relative h-[300px] md:h-[500px] w-full">
                <Image
                  src="/images/blog/blog-56.jpeg"
                  alt="A professional financial advisor"
                  fill
                  className="object-cover"
                  priority
                />
              </div>

              <div className="px-5 py-8 md:px-12 md:py-14">
                <Typography
                  variant="h5"
                  className="text-[#1e3a8a] uppercase text-2xl md:text-4xl mb-4"
                >
                  Loans Are Not Bad When Managed Properly: A Deep Dive into
                  Strategic Debt
                </Typography>

                <div className="flex items-center gap-2 text-gray-400 mb-8 border-b pb-4">
                  <Clock size={16} />
                  <Typography variant="b2">June 25, 2026</Typography>
                </div>

                <article className="prose max-w-none text-gray-600 text-justify space-y-6">
                  <p>
                    For generations, we have been conditioned to view debt as a
                    financial taboo. While staying completely debt-free sounds
                    peaceful, it is often an incomplete approach to building
                    high-level wealth. The reality of modern corporate and
                    personal finance is different:{" "}
                    <strong>loans are not bad when managed properly.</strong>
                  </p>
                  <p>
                    When used strategically, a loan is not a financial trap—it
                    is a powerful lever. It allows you to accelerate growth,
                    acquire appreciating assets, and manage cash flow crunches
                    without liquidating your long-term investments.
                  </p>

                  <h2>
                    1. The Core Philosophy: Shifting from Debt Trap to
                    Strategic Leverage
                  </h2>
                  <p>
                    The golden rule of leverage is simple: if the net return
                    generated by the asset you purchase is higher than the
                    interest rate of the loan, you are building wealth.
                  </p>
                  <ul>
                    <li>
                      <strong>Good Debt:</strong> Loans for assets that grow in
                      value or generate income (e.g., home loans, business
                      expansion, education).
                    </li>
                    <li>
                      <strong>Bad Debt:</strong> Loans for depreciating
                      lifestyle assets (e.g., high-interest credit card debt for
                      vacations or luxury electronics).
                    </li>
                  </ul>

                  <h2>2. The Anatomy of a Healthy Loan Portfolio</h2>
                  <p>
                    To keep debt as an asset rather than a burden, follow the{" "}
                    <strong>35% Debt-to-Income (DTI) Ceiling</strong>. Your
                    total monthly EMIs should never exceed 35% of your net
                    monthly income to remain in the Optimally Leveraged zone.
                  </p>

                  <h2>3. The Triple Benefits of Managing Loans Properly</h2>
                  <ol>
                    <li>
                      <strong>Preservation of Compounding Capital:</strong> By
                      taking a low-interest loan, you avoid breaking your
                      high-yield investments, allowing your core corpus to
                      compound uninterrupted.
                    </li>
                    <li>
                      <strong>Tax Optimization Shields:</strong> Many
                      governments incentivize good debt through interest
                      deductions, effectively lowering your borrowing cost.
                    </li>
                    <li>
                      <strong>Credit Score Amplification:</strong> Responsible
                      repayment is the fastest way to build a flawless credit
                      profile, unlocking better rates for future ventures.
                    </li>
                  </ol>

                  <h2>4. Evaluating a Strategic Loan Opportunity</h2>
                  <p>
                    Before signing any agreement, run it through this
                    verification sequence:
                  </p>
                  <ul>
                    <li>
                      <strong>Define Utility:</strong> Eliminate all lifestyle
                      consumption borrowing.
                    </li>
                    <li>
                      <strong>Interest Rate Arbitrage:</strong> Ensure your
                      investment return rate beats the borrowing cost.
                    </li>
                    <li>
                      <strong>Stress-Test:</strong> Maintain at least 6 months
                      of EMIs in a liquid emergency fund.
                    </li>
                  </ul>

                  <h2>Summary Framework: The Smart Borrower’s Creed</h2>
                  <div className="bg-gray-50 p-6 rounded-xl border border-gray-200">
                    <p>
                      <strong>BAD BORROWING:</strong> Impulsive ➔ Consumer Goods
                      ➔ High Interest ➔ Breaks Cash Flow
                    </p>
                    <p>
                      <strong>SMART LEVERAGE:</strong> Calculated ➔ Appreciating
                      Assets ➔ Tax-Optimized ➔ Builds Credit
                    </p>
                  </div>

                  <div className="bg-gray-50 p-6 rounded-xl border border-gray-200 mt-8">
                    <h2 className="text-[#1e3a8a] text-xl font-bold mb-4 flex items-center gap-2">
                      <HelpCircle size={20} /> Frequently Asked Questions
                    </h2>
                    <ul className="space-y-4">
                      <li>
                        <strong>
                          Q: Is it always better to pay off a loan early?
                        </strong>
                        <br />
                        Not necessarily. If your loan interest rate is low
                        (e.g., 8.5%) and you can invest surplus cash at 12-14%,
                        keeping the loan active can net-increase your total
                        wealth.
                      </li>
                      <li>
                        <strong>
                          Q: How does a personal loan fit into wealth
                          philosophy?
                        </strong>
                        <br />
                        Personal loans should be reserved for high-utility
                        scenarios, such as consolidating high-interest debt or
                        funding business assets that generate immediate revenue.
                      </li>
                      <li>
                        <strong>Q: Can a loan reduce financial anxiety?</strong>
                        <br />
                        Yes, when used as a liquidity cushion. Business loans
                        can smooth out seasonal cycles, ensuring operations run
                        flawlessly without touching your personal safety net.
                      </li>
                    </ul>
                  </div>
                </article>

                <div className="bg-slate-900 text-white p-8 md:p-12 rounded-[40px] mt-10">
                  <Typography
                    variant="h5"
                    className="text-blue-400 uppercase mb-3"
                  >
                    Need Professional Financial Guidance?
                  </Typography>
                  <Typography variant="b2" className="text-gray-300">
                    At Money King Financial Services, we specialize in
                    simplifying complex financial decisions. Contact our team
                    today to get a customized roadmap for your financial goals.
                  </Typography>
                </div>

                <div className="mt-14">
                  <ShareSection />
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
