"use client";

import React, { useState } from "react";
import Image from "next/image";
import NextLink from "next/link";
import { Clock, ArrowLeft, HelpCircle } from "lucide-react";
import { BlogCard1 } from "./BlogCard1";
import { ShareSection } from "./ShareSection";
import { Typography } from "@/app/components/ui/Typography";

export const Blog109: React.FC = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);

  return (
    <div className="w-full flex justify-center">
      {!isOpen ? (
        <div
          onClick={() => setIsOpen(true)}
          className="cursor-pointer w-full flex justify-center px-4"
        >
          <BlogCard1
            title="SIP Interest Rate & Returns: How It Works, Calculation & Compound Growth"
            category="MUTUAL FUNDS"
            author="Kishan Baranwal"
            date="September 22, 2026"
            image="/images/blog/Blog-109.jpeg"
          />
        </div>
      ) : (
        <div className="fixed inset-0 z-40 bg-white overflow-y-auto pt-20 md:pt-28 no-scrollbar animate-in fade-in duration-300 text-left">
          <div className="relative max-w-5xl mx-auto pb-20 px-4 md:px-6">
            {/* Back Button */}
            <button
              onClick={() => setIsOpen(false)}
              className="flex items-center mb-6 text-gray-500 hover:text-[#1e3a8a] transition-colors gap-1"
            >
              <ArrowLeft size={14} />
              <Typography variant="caption" className="font-bold uppercase">
                Back to Blogs
              </Typography>
            </button>

            {/* Main Blog Container */}
            <div className="bg-white rounded-xl overflow-hidden border border-gray-100 shadow-sm">
              {/* Professional Image Preview Section */}
              <div className="w-full flex justify-center bg-slate-50 py-4 px-4 border-b border-gray-100">
                <div className="relative w-full max-w-3xl aspect-[16/9] rounded-lg overflow-hidden shadow-md">
                  <Image
                    src="/images/blog/Blog-109.jpeg"
                    alt="SIP Interest Rate Calculation and Returns"
                    fill
                    className="object-cover"
                    priority
                  />
                </div>
              </div>

              <div className="px-5 py-8 md:px-12 md:py-14">
                <Typography
                  variant="h5"
                  className="text-[#1e3a8a] uppercase text-2xl md:text-4xl mb-4 font-bold"
                >
                  <NextLink
                    href="https://moneykingfinancial.com/services/mutual-fund/sip"
                    className="text-[#1e3a8a] hover:underline"
                  >
                    SIP Interest Rate
                  </NextLink>
                  &amp; Returns: How It Works, Calculation &amp; Compound Growth
                </Typography>

                <div className="flex items-center gap-2 text-gray-400 mb-8 border-b pb-4">
                  <Clock size={16} />
                  <Typography variant="b2">September 22, 2026</Typography>
                </div>

                {/* Blog Article Body */}
                <article className="prose max-w-none text-gray-600 text-justify space-y-6">
                  {/* Featured Snippet Box */}
                  <div className="bg-slate-50 border-l-4 border-[#1e3a8a] p-4 rounded-r-lg">
                    <p className="text-gray-700 italic m-0">
                      Unlike fixed bank deposits, a Systematic Investment Plan (SIP) does not offer a fixed or guaranteed interest rate. Instead, SIP returns are market-linked capital gains generated by underlying mutual funds. Over long-term horizons (5 to 10+ years), equity{" "}
                      <NextLink
                        href="https://moneykingfinancial.com/services/mutual-fund/sip"
                        className="text-blue-600 font-semibold hover:underline"
                      >
                        SIPs
                      </NextLink>{" "}
                      typically generate annualized returns (XIRR) ranging between 12% and 15%, driven by market compounding and rupee cost averaging.
                    </p>
                  </div>

                  <p>
                    A Systematic Investment Plan (SIP) is one of the most popular ways to build wealth systematically over time. It allows investors to allocate a fixed sum of money into mutual funds at regular intervals (monthly, quarterly, or weekly).
                  </p>

                  <p>
                    A common question among new investors is: &quot;What is the interest rate of a SIP?&quot;
                  </p>

                  <p>
                    Technically, SIPs do not pay fixed interest like a savings account or Fixed Deposit (FD). Instead, your money grows through market appreciation, dividends, and compounding returns. Here is a complete guide to understanding how SIP returns work, how they are calculated, and how to maximize your wealth creation through our{" "}
                    <NextLink
                      href="https://moneykingfinancial.com/"
                      className="text-blue-600 font-semibold hover:underline"
                    >
                      Money King Financial Portal
                    </NextLink>
                    .
                  </p>

                  <h2 className="text-xl font-bold text-gray-800 pt-4">
                    Key Differences: Fixed Deposit Interest vs. SIP Returns
                  </h2>
                  <p>
                    Understanding how SIP returns differ from traditional guaranteed savings instruments helps set realistic expectations:
                  </p>

                  <div className="overflow-x-auto my-6">
                    <table className="w-full border-collapse border border-gray-200">
                      <thead>
                        <tr className="bg-gray-100 text-left">
                          <th className="border p-2">Feature</th>
                          <th className="border p-2">Bank Fixed Deposit (FD)</th>
                          <th className="border p-2">Mutual Fund SIP</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td className="border p-2 font-bold">Return Type</td>
                          <td className="border p-2">Guaranteed Fixed Interest</td>
                          <td className="border p-2 font-semibold text-green-600">Market-Linked Capital Gains</td>
                        </tr>
                        <tr>
                          <td className="border p-2 font-bold">Average Return Rate</td>
                          <td className="border p-2">6.5% – 7.5% per annum</td>
                          <td className="border p-2">12% – 15% (Historical Equity Average)</td>
                        </tr>
                        <tr>
                          <td className="border p-2 font-bold">Impact of Inflation</td>
                          <td className="border p-2">Minimal or negative real returns</td>
                          <td className="border p-2">High potential to beat inflation long-term</td>
                        </tr>
                        <tr>
                          <td className="border p-2 font-bold">Flexibility</td>
                          <td className="border p-2">Fixed tenure with premature withdrawal penalties</td>
                          <td className="border p-2">Pause, increase, or stop anytime without penalties (open-ended)</td>
                        </tr>
                        <tr>
                          <td className="border p-2 font-bold">Risk Level</td>
                          <td className="border p-2">Low Risk</td>
                          <td className="border p-2">Market Risk (Mitigated over long tenures)</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <h2 className="text-xl font-bold text-gray-800 pt-4">
                    How Are SIP Returns Calculated? (XIRR vs. CAGR)
                  </h2>
                  <p>
                    Because an investor deposits money in multiple installments across different market levels rather than a lump sum, standard interest formulas (A = P(1 + r/n)^nt) do not accurately measure SIP performance.
                  </p>
                  <p>
                    Financial institutions use two key metrics:
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>
                      <strong>1. Compound Annual Growth Rate (CAGR):</strong> CAGR measures the annual growth rate of an investment over a specified period. However, CAGR assumes a single lump-sum investment made at the very beginning and is not ideal for calculating multi-installment SIP returns.
                    </li>
                    <li>
                      <strong>2. Extended Internal Rate of Return (XIRR):</strong> XIRR is the standard and most accurate metric for SIP return calculations. It evaluates every individual installment as a separate cash flow made on a specific date and calculates the consolidated annualized return percentage across all deposits.
                    </li>
                  </ul>

                  <h2 className="text-xl font-bold text-gray-800 pt-4">
                    The Two Core Engines of SIP Wealth Creation
                  </h2>
                  <ul className="list-disc pl-6 space-y-2">
                    <li>
                      <strong>A. Rupee Cost Averaging:</strong> When the market goes down, your monthly SIP installment buys more mutual fund units. When the market goes up, the value of those accumulated units increases. This eliminates the need to &quot;time the market&quot; and lowers the average cost per unit over time.
                    </li>
                    <li>
                      <strong>B. Power of Compounding:</strong> In a mutual fund SIP, returns earned in year 1 generate additional returns in year 2. Over extended horizons (10 to 20 years), this compounding effect causes growth to accelerate exponentially.
                    </li>
                  </ul>

                  <h2 className="text-xl font-bold text-gray-800 pt-4">
                    Expected Historical SIP Returns Across Asset Classes
                  </h2>
                  <p>
                    While past performance does not guarantee future results, historical long-term averages in India provide a helpful baseline through our{" "}
                    <NextLink
                      href="https://moneykingfinancial.com/services/mutual-fund/sip"
                      className="text-blue-600 font-semibold hover:underline"
                    >
                      SIP Investment Services
                    </NextLink>
                    :
                  </p>
                  <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Equity Mutual Funds (Large Cap / Index):</strong> ~11% to 13% p.a.</li>
                    <li><strong>Flexi Cap / Mid Cap Mutual Funds:</strong> ~13% to 16% p.a.</li>
                    <li><strong>Hybrid / Balanced Advantage Funds:</strong> ~9% to 11% p.a.</li>
                    <li><strong>Debt Mutual Funds:</strong> ~6% to 8% p.a.</li>
                  </ul>

                  {/* FAQ Section */}
                  <div className="bg-gray-50 p-6 rounded-xl border border-gray-200 mt-8">
                    <h2 className="text-[#1e3a8a] text-xl font-bold mb-4 flex items-center gap-2">
                      <HelpCircle size={20} /> Frequently Asked Questions (FAQ)
                    </h2>
                    <ul className="space-y-4">
                      <li>
                        <strong>Q1: What is the average interest rate of a 5-year SIP?</strong>
                        <br />
                        Equity SIPs historically deliver an annualized return (XIRR) of 12% to 15% over a 5-year to 10-year period, though short-term market fluctuations can cause temporary volatility.
                      </li>
                      <li>
                        <strong>Q2: Can I lose money in a SIP?</strong>
                        <br />
                        Since equity SIPs invest in stock markets, unit values fluctuate short-term. However, holding an equity SIP for 5 to 7+ years significantly reduces the risk of negative returns due to rupee cost averaging.
                      </li>
                      <li>
                        <strong>Q3: What is the Step-Up SIP feature?</strong>
                        <br />
                        A Step-Up (or Top-Up) SIP allows you to automatically increase your monthly investment amount by a fixed percentage or amount every year (e.g., increasing your SIP by 10% annually with salary hikes), accelerating your wealth accumulation.
                      </li>
                      <li>
                        <strong>Q4: Are SIP returns taxable?</strong>
                        <br />
                        Yes. For Equity Mutual Funds, short-term capital gains (held &lt; 1 year) are taxed at 20%. Long-term capital gains (held &gt; 1 year) exceeding ₹1.25 Lakh in a financial year are taxed at 12.5% without indexation benefits.
                      </li>
                    </ul>
                  </div>
                </article>

                {/* Call To Action Banner */}
                <div className="bg-slate-900 text-white p-8 md:p-12 rounded-[40px] mt-10">
                  <Typography
                    variant="h5"
                    className="text-blue-400 uppercase mb-3 font-bold"
                  >
                    Start Your SIP Journey Today and Grow Your Wealth!
                  </Typography>
                  <Typography variant="b2" className="text-gray-300 mb-6 block">
                    Maximize your compounding benefits and beat inflation with professional mutual fund guidance from{" "}
                    <NextLink
                      href="https://moneykingfinancial.com/"
                      className="text-blue-400 hover:underline"
                    >
                      Money King Financial Services
                    </NextLink>
                    .
                  </Typography>

                  <div className="flex flex-wrap gap-4 mt-2">
                    <NextLink
                      href="https://moneykingfinancial.com/services/mutual-fund/sip"
                      className="inline-block bg-blue-600 text-white font-bold px-8 py-3 rounded-xl hover:bg-blue-700 transition"
                    >
                      Start SIP Now
                    </NextLink>
                  </div>
                </div>

                <div className="mt-14">
                  <ShareSection />
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};